'----------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'----------------------

Option Explicit On
Option Strict On

Imports System
Imports System.Diagnostics
Imports System.Windows
Imports System.Windows.Automation
Imports System.Windows.Controls
Imports System.Windows.Controls.Primitives
Imports System.Windows.Data
Imports System.Windows.Documents
Imports System.Windows.Ink
Imports System.Windows.Input
Imports System.Windows.Markup
Imports System.Windows.Media
Imports System.Windows.Media.Animation
Imports System.Windows.Media.Effects
Imports System.Windows.Media.Imaging
Imports System.Windows.Media.Media3D
Imports System.Windows.Media.TextFormatting
Imports System.Windows.Navigation
Imports System.Windows.Shapes

Partial Class MainWindow

    Friend WithEvents lstGaleria As ListBox
    Friend WithEvents VisualizadorVideo As MediaElement
    Friend WithEvents btnFrameAnterior As Button
    Friend WithEvents btnPlayPause As Button
    Friend WithEvents btnFrameProximo As Button
    Friend WithEvents btnModoCrono As ToggleButton
    Friend WithEvents lblTempoAtual As TextBlock
    Friend WithEvents slLinhaTempo As Slider
    Friend WithEvents canvasCorte As Canvas
    Friend WithEvents bdrCorte As Border
    Friend WithEvents popupTempoDrag As Popup
    Friend WithEvents lblTempoDrag As TextBlock
    Friend WithEvents lblTempoTotal As TextBlock
    Friend WithEvents txtInicio As TextBox
    Friend WithEvents txtFim As TextBox
    Friend WithEvents rbNormal As RadioButton
    Friend WithEvents rbRotDireita As RadioButton
    Friend WithEvents rbRotEsquerda As RadioButton
    Friend WithEvents rbRot180 As RadioButton
    Friend WithEvents rbEspelharH As RadioButton
    Friend WithEvents rbEspelharV As RadioButton
    Friend WithEvents grpConfigVideo As GroupBox
    Friend WithEvents painelExportacao As StackPanel
    Friend WithEvents pnlCrono As Border
    Friend WithEvents gridCrono As DataGrid
    Friend WithEvents btnNovaOperacao As Button
    Friend WithEvents btnExportarCrono As Button
    Friend WithEvents btnLimparCrono As Button
    Friend WithEvents rbDesempenhoAlto As RadioButton
    Friend WithEvents rbDesempenhoEco As RadioButton
    Friend WithEvents rbSalvarPastaOriginal As RadioButton
    Friend WithEvents rbSalvarPastaEscolhida As RadioButton
    Friend WithEvents chkDeletarOriginal As CheckBox
    Friend WithEvents btnProcessar As Button
    Friend WithEvents pbProgresso As ProgressBar
    Friend WithEvents lblStatusLote As TextBlock
    Friend WithEvents lblPorcentagem As TextBlock
    Friend WithEvents painelProgresso As StackPanel
    Friend WithEvents expExportacaoDesempenho As Expander

    Public Sub InitializeComponent()
        If Me._contentLoaded Then
            Return
        End If
        Me._contentLoaded = True
        Dim resourceLocater As System.Uri = New System.Uri("/Editor de vídeos;component/mainwindow.xaml", System.UriKind.Relative)
        System.Windows.Application.LoadComponent(Me, resourceLocater)
    End Sub

    <System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "15.0.0.0")>
    Public Sub ConnectUI()
        Me.lstGaleria = CType(Me.FindName("lstGaleria"), ListBox)
        Me.VisualizadorVideo = CType(Me.FindName("VisualizadorVideo"), MediaElement)
        Me.btnFrameAnterior = CType(Me.FindName("btnFrameAnterior"), Button)
        Me.btnPlayPause = CType(Me.FindName("btnPlayPause"), Button)
        Me.btnFrameProximo = CType(Me.FindName("btnFrameProximo"), Button)
        Me.btnModoCrono = CType(Me.FindName("btnModoCrono"), ToggleButton)
        Me.lblTempoAtual = CType(Me.FindName("lblTempoAtual"), TextBlock)
        Me.slLinhaTempo = CType(Me.FindName("slLinhaTempo"), Slider)
        Me.canvasCorte = CType(Me.FindName("canvasCorte"), Canvas)
        Me.bdrCorte = CType(Me.FindName("bdrCorte"), Border)
        Me.popupTempoDrag = CType(Me.FindName("popupTempoDrag"), Popup)
        Me.lblTempoDrag = CType(Me.FindName("lblTempoDrag"), TextBlock)
        Me.lblTempoTotal = CType(Me.FindName("lblTempoTotal"), TextBlock)
        Me.txtInicio = CType(Me.FindName("txtInicio"), TextBox)
        Me.txtFim = CType(Me.FindName("txtFim"), TextBox)
        Me.rbNormal = CType(Me.FindName("rbNormal"), RadioButton)
        Me.rbRotDireita = CType(Me.FindName("rbRotDireita"), RadioButton)
        Me.rbRotEsquerda = CType(Me.FindName("rbRotEsquerda"), RadioButton)
        Me.rbRot180 = CType(Me.FindName("rbRot180"), RadioButton)
        Me.rbEspelharH = CType(Me.FindName("rbEspelharH"), RadioButton)
        Me.rbEspelharV = CType(Me.FindName("rbEspelharV"), RadioButton)
        Me.grpConfigVideo = CType(Me.FindName("grpConfigVideo"), GroupBox)
        Me.painelExportacao = CType(Me.FindName("painelExportacao"), StackPanel)
        Me.pnlCrono = CType(Me.FindName("pnlCrono"), Border)
        Me.gridCrono = CType(Me.FindName("gridCrono"), DataGrid)
        Me.btnNovaOperacao = CType(Me.FindName("btnNovaOperacao"), Button)
        Me.btnExportarCrono = CType(Me.FindName("btnExportarCrono"), Button)
        Me.btnLimparCrono = CType(Me.FindName("btnLimparCrono"), Button)
        Me.rbDesempenhoAlto = CType(Me.FindName("rbDesempenhoAlto"), RadioButton)
        Me.rbDesempenhoEco = CType(Me.FindName("rbDesempenhoEco"), RadioButton)
        Me.rbSalvarPastaOriginal = CType(Me.FindName("rbSalvarPastaOriginal"), RadioButton)
        Me.rbSalvarPastaEscolhida = CType(Me.FindName("rbSalvarPastaEscolhida"), RadioButton)
        Me.chkDeletarOriginal = CType(Me.FindName("chkDeletarOriginal"), CheckBox)
        Me.btnProcessar = CType(Me.FindName("btnProcessar"), Button)
        Me.pbProgresso = CType(Me.FindName("pbProgresso"), ProgressBar)
        Me.lblStatusLote = CType(Me.FindName("lblStatusLote"), TextBlock)
        Me.lblPorcentagem = CType(Me.FindName("lblPorcentagem"), TextBlock)
        Me.painelProgresso = CType(Me.FindName("painelProgresso"), StackPanel)
        Me.expExportacaoDesempenho = CType(Me.FindName("expExportacaoDesempenho"), Expander)
    End Sub

    Private _contentLoaded As Boolean = False

End Class
